// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sprints.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sprints.proto

It has these top-level messages:
	Empty
	AbortMessage
	Race
	DefinedRace
	Results
	Result
	DefinedPlayer
	ResultSpec
	Player
	Starter
	Racer
	Tournament
	VisConfiguration
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
	Gender_OTHER  Gender = 2
)

var Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
	2: "OTHER",
}
var Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
	"OTHER":  2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Tournament_TournamentMode int32

const (
	Tournament_DISTANCE Tournament_TournamentMode = 0
	Tournament_TIME     Tournament_TournamentMode = 1
)

var Tournament_TournamentMode_name = map[int32]string{
	0: "DISTANCE",
	1: "TIME",
}
var Tournament_TournamentMode_value = map[string]int32{
	"DISTANCE": 0,
	"TIME":     1,
}

func (x Tournament_TournamentMode) String() string {
	return proto.EnumName(Tournament_TournamentMode_name, int32(x))
}
func (Tournament_TournamentMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AbortMessage struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *AbortMessage) Reset()                    { *m = AbortMessage{} }
func (m *AbortMessage) String() string            { return proto.CompactTextString(m) }
func (*AbortMessage) ProtoMessage()               {}
func (*AbortMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AbortMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Race struct {
	Players   []*Player `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	DestValue uint32    `protobuf:"varint,2,opt,name=destValue" json:"destValue,omitempty"`
}

func (m *Race) Reset()                    { *m = Race{} }
func (m *Race) String() string            { return proto.CompactTextString(m) }
func (*Race) ProtoMessage()               {}
func (*Race) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Race) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Race) GetDestValue() uint32 {
	if m != nil {
		return m.DestValue
	}
	return 0
}

type DefinedRace struct {
	// how many races are remaining before this one will take place
	RacesRemaining uint32           `protobuf:"varint,1,opt,name=racesRemaining" json:"racesRemaining,omitempty"`
	Player         []*DefinedPlayer `protobuf:"bytes,2,rep,name=player" json:"player,omitempty"`
}

func (m *DefinedRace) Reset()                    { *m = DefinedRace{} }
func (m *DefinedRace) String() string            { return proto.CompactTextString(m) }
func (*DefinedRace) ProtoMessage()               {}
func (*DefinedRace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DefinedRace) GetRacesRemaining() uint32 {
	if m != nil {
		return m.RacesRemaining
	}
	return 0
}

func (m *DefinedRace) GetPlayer() []*DefinedPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

type Results struct {
	Result []*Result `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *Results) Reset()                    { *m = Results{} }
func (m *Results) String() string            { return proto.CompactTextString(m) }
func (*Results) ProtoMessage()               {}
func (*Results) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Results) GetResult() []*Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Result struct {
	Player    *Player `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
	Result    float32 `protobuf:"fixed32,2,opt,name=result" json:"result,omitempty"`
	DestValue uint32  `protobuf:"varint,3,opt,name=destValue" json:"destValue,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Result) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *Result) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *Result) GetDestValue() uint32 {
	if m != nil {
		return m.DestValue
	}
	return 0
}

type DefinedPlayer struct {
	Color           string           `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
	RacesRemaining  uint32           `protobuf:"varint,2,opt,name=racesRemaining" json:"racesRemaining,omitempty"`
	OtherContenders []*DefinedPlayer `protobuf:"bytes,3,rep,name=otherContenders" json:"otherContenders,omitempty"`
}

func (m *DefinedPlayer) Reset()                    { *m = DefinedPlayer{} }
func (m *DefinedPlayer) String() string            { return proto.CompactTextString(m) }
func (*DefinedPlayer) ProtoMessage()               {}
func (*DefinedPlayer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DefinedPlayer) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *DefinedPlayer) GetRacesRemaining() uint32 {
	if m != nil {
		return m.RacesRemaining
	}
	return 0
}

func (m *DefinedPlayer) GetOtherContenders() []*DefinedPlayer {
	if m != nil {
		return m.OtherContenders
	}
	return nil
}

type ResultSpec struct {
	Gender         Gender `protobuf:"varint,1,opt,name=gender,enum=pb.Gender" json:"gender,omitempty"`
	Last           uint32 `protobuf:"varint,2,opt,name=last" json:"last,omitempty"`
	TournamentName string `protobuf:"bytes,3,opt,name=tournamentName" json:"tournamentName,omitempty"`
}

func (m *ResultSpec) Reset()                    { *m = ResultSpec{} }
func (m *ResultSpec) String() string            { return proto.CompactTextString(m) }
func (*ResultSpec) ProtoMessage()               {}
func (*ResultSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ResultSpec) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

func (m *ResultSpec) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *ResultSpec) GetTournamentName() string {
	if m != nil {
		return m.TournamentName
	}
	return ""
}

type Player struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Gender Gender `protobuf:"varint,2,opt,name=gender,enum=pb.Gender" json:"gender,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

type Starter struct {
	CountdownTime uint32 `protobuf:"varint,1,opt,name=countdownTime" json:"countdownTime,omitempty"`
}

func (m *Starter) Reset()                    { *m = Starter{} }
func (m *Starter) String() string            { return proto.CompactTextString(m) }
func (*Starter) ProtoMessage()               {}
func (*Starter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Starter) GetCountdownTime() uint32 {
	if m != nil {
		return m.CountdownTime
	}
	return 0
}

type Racer struct {
	PlayerNum uint32 `protobuf:"varint,1,opt,name=playerNum" json:"playerNum,omitempty"`
	Distance  uint32 `protobuf:"varint,2,opt,name=distance" json:"distance,omitempty"`
}

func (m *Racer) Reset()                    { *m = Racer{} }
func (m *Racer) String() string            { return proto.CompactTextString(m) }
func (*Racer) ProtoMessage()               {}
func (*Racer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Racer) GetPlayerNum() uint32 {
	if m != nil {
		return m.PlayerNum
	}
	return 0
}

func (m *Racer) GetDistance() uint32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type Tournament struct {
	Name        string                    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DestValue   uint32                    `protobuf:"varint,3,opt,name=destValue" json:"destValue,omitempty"`
	Mode        Tournament_TournamentMode `protobuf:"varint,4,opt,name=mode,enum=pb.Tournament_TournamentMode" json:"mode,omitempty"`
	PlayerCount uint32                    `protobuf:"varint,5,opt,name=playerCount" json:"playerCount,omitempty"`
	Color       []string                  `protobuf:"bytes,6,rep,name=color" json:"color,omitempty"`
}

func (m *Tournament) Reset()                    { *m = Tournament{} }
func (m *Tournament) String() string            { return proto.CompactTextString(m) }
func (*Tournament) ProtoMessage()               {}
func (*Tournament) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Tournament) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tournament) GetDestValue() uint32 {
	if m != nil {
		return m.DestValue
	}
	return 0
}

func (m *Tournament) GetMode() Tournament_TournamentMode {
	if m != nil {
		return m.Mode
	}
	return Tournament_DISTANCE
}

func (m *Tournament) GetPlayerCount() uint32 {
	if m != nil {
		return m.PlayerCount
	}
	return 0
}

func (m *Tournament) GetColor() []string {
	if m != nil {
		return m.Color
	}
	return nil
}

type VisConfiguration struct {
	HostName         string `protobuf:"bytes,1,opt,name=hostName" json:"hostName,omitempty"`
	VisName          string `protobuf:"bytes,2,opt,name=visName" json:"visName,omitempty"`
	Fullscreen       bool   `protobuf:"varint,3,opt,name=fullscreen" json:"fullscreen,omitempty"`
	ResolutionWidth  uint32 `protobuf:"varint,4,opt,name=resolutionWidth" json:"resolutionWidth,omitempty"`
	ResolutionHeight uint32 `protobuf:"varint,5,opt,name=resolutionHeight" json:"resolutionHeight,omitempty"`
	MovingUnit       uint32 `protobuf:"varint,6,opt,name=movingUnit" json:"movingUnit,omitempty"`
}

func (m *VisConfiguration) Reset()                    { *m = VisConfiguration{} }
func (m *VisConfiguration) String() string            { return proto.CompactTextString(m) }
func (*VisConfiguration) ProtoMessage()               {}
func (*VisConfiguration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *VisConfiguration) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *VisConfiguration) GetVisName() string {
	if m != nil {
		return m.VisName
	}
	return ""
}

func (m *VisConfiguration) GetFullscreen() bool {
	if m != nil {
		return m.Fullscreen
	}
	return false
}

func (m *VisConfiguration) GetResolutionWidth() uint32 {
	if m != nil {
		return m.ResolutionWidth
	}
	return 0
}

func (m *VisConfiguration) GetResolutionHeight() uint32 {
	if m != nil {
		return m.ResolutionHeight
	}
	return 0
}

func (m *VisConfiguration) GetMovingUnit() uint32 {
	if m != nil {
		return m.MovingUnit
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*AbortMessage)(nil), "pb.AbortMessage")
	proto.RegisterType((*Race)(nil), "pb.Race")
	proto.RegisterType((*DefinedRace)(nil), "pb.DefinedRace")
	proto.RegisterType((*Results)(nil), "pb.Results")
	proto.RegisterType((*Result)(nil), "pb.Result")
	proto.RegisterType((*DefinedPlayer)(nil), "pb.DefinedPlayer")
	proto.RegisterType((*ResultSpec)(nil), "pb.ResultSpec")
	proto.RegisterType((*Player)(nil), "pb.Player")
	proto.RegisterType((*Starter)(nil), "pb.Starter")
	proto.RegisterType((*Racer)(nil), "pb.Racer")
	proto.RegisterType((*Tournament)(nil), "pb.Tournament")
	proto.RegisterType((*VisConfiguration)(nil), "pb.VisConfiguration")
	proto.RegisterEnum("pb.Gender", Gender_name, Gender_value)
	proto.RegisterEnum("pb.Tournament_TournamentMode", Tournament_TournamentMode_name, Tournament_TournamentMode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sprints service

type SprintsClient interface {
	NewTournament(ctx context.Context, in *Tournament, opts ...grpc.CallOption) (*Tournament, error)
	NewRace(ctx context.Context, in *Race, opts ...grpc.CallOption) (*Empty, error)
	StartRace(ctx context.Context, in *Starter, opts ...grpc.CallOption) (*Empty, error)
	AbortRace(ctx context.Context, in *AbortMessage, opts ...grpc.CallOption) (*Empty, error)
	ConfigureVis(ctx context.Context, in *VisConfiguration, opts ...grpc.CallOption) (*Empty, error)
	GetResults(ctx context.Context, in *ResultSpec, opts ...grpc.CallOption) (Sprints_GetResultsClient, error)
	GetTournaments(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Sprints_GetTournamentsClient, error)
}

type sprintsClient struct {
	cc *grpc.ClientConn
}

func NewSprintsClient(cc *grpc.ClientConn) SprintsClient {
	return &sprintsClient{cc}
}

func (c *sprintsClient) NewTournament(ctx context.Context, in *Tournament, opts ...grpc.CallOption) (*Tournament, error) {
	out := new(Tournament)
	err := grpc.Invoke(ctx, "/pb.Sprints/NewTournament", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintsClient) NewRace(ctx context.Context, in *Race, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Sprints/NewRace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintsClient) StartRace(ctx context.Context, in *Starter, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Sprints/StartRace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintsClient) AbortRace(ctx context.Context, in *AbortMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Sprints/AbortRace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintsClient) ConfigureVis(ctx context.Context, in *VisConfiguration, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Sprints/ConfigureVis", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintsClient) GetResults(ctx context.Context, in *ResultSpec, opts ...grpc.CallOption) (Sprints_GetResultsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Sprints_serviceDesc.Streams[0], c.cc, "/pb.Sprints/GetResults", opts...)
	if err != nil {
		return nil, err
	}
	x := &sprintsGetResultsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Sprints_GetResultsClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type sprintsGetResultsClient struct {
	grpc.ClientStream
}

func (x *sprintsGetResultsClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sprintsClient) GetTournaments(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Sprints_GetTournamentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Sprints_serviceDesc.Streams[1], c.cc, "/pb.Sprints/GetTournaments", opts...)
	if err != nil {
		return nil, err
	}
	x := &sprintsGetTournamentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Sprints_GetTournamentsClient interface {
	Recv() (*Tournament, error)
	grpc.ClientStream
}

type sprintsGetTournamentsClient struct {
	grpc.ClientStream
}

func (x *sprintsGetTournamentsClient) Recv() (*Tournament, error) {
	m := new(Tournament)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Sprints service

type SprintsServer interface {
	NewTournament(context.Context, *Tournament) (*Tournament, error)
	NewRace(context.Context, *Race) (*Empty, error)
	StartRace(context.Context, *Starter) (*Empty, error)
	AbortRace(context.Context, *AbortMessage) (*Empty, error)
	ConfigureVis(context.Context, *VisConfiguration) (*Empty, error)
	GetResults(*ResultSpec, Sprints_GetResultsServer) error
	GetTournaments(*Empty, Sprints_GetTournamentsServer) error
}

func RegisterSprintsServer(s *grpc.Server, srv SprintsServer) {
	s.RegisterService(&_Sprints_serviceDesc, srv)
}

func _Sprints_NewTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tournament)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintsServer).NewTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sprints/NewTournament",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintsServer).NewTournament(ctx, req.(*Tournament))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sprints_NewRace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Race)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintsServer).NewRace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sprints/NewRace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintsServer).NewRace(ctx, req.(*Race))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sprints_StartRace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Starter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintsServer).StartRace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sprints/StartRace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintsServer).StartRace(ctx, req.(*Starter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sprints_AbortRace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintsServer).AbortRace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sprints/AbortRace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintsServer).AbortRace(ctx, req.(*AbortMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sprints_ConfigureVis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintsServer).ConfigureVis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sprints/ConfigureVis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintsServer).ConfigureVis(ctx, req.(*VisConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sprints_GetResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResultSpec)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SprintsServer).GetResults(m, &sprintsGetResultsServer{stream})
}

type Sprints_GetResultsServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type sprintsGetResultsServer struct {
	grpc.ServerStream
}

func (x *sprintsGetResultsServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func _Sprints_GetTournaments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SprintsServer).GetTournaments(m, &sprintsGetTournamentsServer{stream})
}

type Sprints_GetTournamentsServer interface {
	Send(*Tournament) error
	grpc.ServerStream
}

type sprintsGetTournamentsServer struct {
	grpc.ServerStream
}

func (x *sprintsGetTournamentsServer) Send(m *Tournament) error {
	return x.ServerStream.SendMsg(m)
}

var _Sprints_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sprints",
	HandlerType: (*SprintsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTournament",
			Handler:    _Sprints_NewTournament_Handler,
		},
		{
			MethodName: "NewRace",
			Handler:    _Sprints_NewRace_Handler,
		},
		{
			MethodName: "StartRace",
			Handler:    _Sprints_StartRace_Handler,
		},
		{
			MethodName: "AbortRace",
			Handler:    _Sprints_AbortRace_Handler,
		},
		{
			MethodName: "ConfigureVis",
			Handler:    _Sprints_ConfigureVis_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetResults",
			Handler:       _Sprints_GetResults_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTournaments",
			Handler:       _Sprints_GetTournaments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sprints.proto",
}

// Client API for Races service

type RacesClient interface {
	UpdateRace(ctx context.Context, opts ...grpc.CallOption) (Races_UpdateRaceClient, error)
	FinishRace(ctx context.Context, in *Results, opts ...grpc.CallOption) (*Empty, error)
	ShowResults(ctx context.Context, in *Results, opts ...grpc.CallOption) (*Empty, error)
	StopVis(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type racesClient struct {
	cc *grpc.ClientConn
}

func NewRacesClient(cc *grpc.ClientConn) RacesClient {
	return &racesClient{cc}
}

func (c *racesClient) UpdateRace(ctx context.Context, opts ...grpc.CallOption) (Races_UpdateRaceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Races_serviceDesc.Streams[0], c.cc, "/pb.Races/UpdateRace", opts...)
	if err != nil {
		return nil, err
	}
	x := &racesUpdateRaceClient{stream}
	return x, nil
}

type Races_UpdateRaceClient interface {
	Send(*Racer) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type racesUpdateRaceClient struct {
	grpc.ClientStream
}

func (x *racesUpdateRaceClient) Send(m *Racer) error {
	return x.ClientStream.SendMsg(m)
}

func (x *racesUpdateRaceClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *racesClient) FinishRace(ctx context.Context, in *Results, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Races/FinishRace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *racesClient) ShowResults(ctx context.Context, in *Results, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Races/ShowResults", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *racesClient) StopVis(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Races/StopVis", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Races service

type RacesServer interface {
	UpdateRace(Races_UpdateRaceServer) error
	FinishRace(context.Context, *Results) (*Empty, error)
	ShowResults(context.Context, *Results) (*Empty, error)
	StopVis(context.Context, *Empty) (*Empty, error)
}

func RegisterRacesServer(s *grpc.Server, srv RacesServer) {
	s.RegisterService(&_Races_serviceDesc, srv)
}

func _Races_UpdateRace_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RacesServer).UpdateRace(&racesUpdateRaceServer{stream})
}

type Races_UpdateRaceServer interface {
	SendAndClose(*Empty) error
	Recv() (*Racer, error)
	grpc.ServerStream
}

type racesUpdateRaceServer struct {
	grpc.ServerStream
}

func (x *racesUpdateRaceServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *racesUpdateRaceServer) Recv() (*Racer, error) {
	m := new(Racer)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Races_FinishRace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Results)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RacesServer).FinishRace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Races/FinishRace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RacesServer).FinishRace(ctx, req.(*Results))
	}
	return interceptor(ctx, in, info, handler)
}

func _Races_ShowResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Results)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RacesServer).ShowResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Races/ShowResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RacesServer).ShowResults(ctx, req.(*Results))
	}
	return interceptor(ctx, in, info, handler)
}

func _Races_StopVis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RacesServer).StopVis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Races/StopVis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RacesServer).StopVis(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Races_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Races",
	HandlerType: (*RacesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FinishRace",
			Handler:    _Races_FinishRace_Handler,
		},
		{
			MethodName: "ShowResults",
			Handler:    _Races_ShowResults_Handler,
		},
		{
			MethodName: "StopVis",
			Handler:    _Races_StopVis_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateRace",
			Handler:       _Races_UpdateRace_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sprints.proto",
}

func init() { proto.RegisterFile("sprints.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x2e, 0x69, 0x89, 0x12, 0x47, 0xa6, 0xa2, 0x2e, 0x82, 0x82, 0x30, 0xda, 0x54, 0x60, 0xdd,
	0x82, 0x31, 0x10, 0x3b, 0x75, 0x1f, 0xfb, 0x52, 0x43, 0x51, 0x9c, 0x14, 0x95, 0x5a, 0x50, 0x8a,
	0xfb, 0x5a, 0x8a, 0x5c, 0x4b, 0x0b, 0x90, 0xbb, 0x04, 0x77, 0x19, 0xc1, 0x57, 0xe8, 0x15, 0x7a,
	0x8e, 0x9e, 0xa4, 0xef, 0x3d, 0x4b, 0xb1, 0x3f, 0x14, 0x29, 0xd6, 0xce, 0xdb, 0xec, 0x37, 0xa3,
	0x99, 0xef, 0x9b, 0x19, 0x8e, 0xc0, 0xe3, 0x45, 0x49, 0xa8, 0xe0, 0x97, 0x45, 0xc9, 0x04, 0x43,
	0x76, 0xb1, 0x09, 0x06, 0xd0, 0x9f, 0xe7, 0x85, 0x78, 0x08, 0x42, 0x38, 0xbd, 0xd9, 0xb0, 0x52,
	0x2c, 0x30, 0xe7, 0xf1, 0x16, 0x23, 0x1f, 0x06, 0xb9, 0x36, 0x7d, 0x6b, 0x6a, 0x85, 0x6e, 0x54,
	0x3f, 0x83, 0x9f, 0xa1, 0x17, 0xc5, 0x09, 0x46, 0xe7, 0x30, 0x28, 0xb2, 0xf8, 0x01, 0x97, 0xdc,
	0xb7, 0xa6, 0x27, 0xe1, 0xe8, 0x1a, 0x2e, 0x8b, 0xcd, 0xe5, 0x6f, 0x0a, 0x8a, 0x6a, 0x17, 0xfa,
	0x12, 0xdc, 0x14, 0x73, 0x71, 0x17, 0x67, 0x15, 0xf6, 0xed, 0xa9, 0x15, 0x7a, 0x51, 0x03, 0x04,
	0x7f, 0xc0, 0xe8, 0x0d, 0xbe, 0x27, 0x14, 0xa7, 0x2a, 0xe5, 0x77, 0x30, 0x2e, 0xe3, 0x04, 0xf3,
	0x08, 0xe7, 0x31, 0xa1, 0x84, 0x6e, 0x55, 0x6d, 0x2f, 0xea, 0xa0, 0xe8, 0x25, 0x38, 0x3a, 0xbf,
	0x6f, 0xab, 0xca, 0x9f, 0xcb, 0xca, 0x26, 0x91, 0x21, 0x60, 0x02, 0x82, 0x57, 0x30, 0x88, 0x30,
	0xaf, 0x32, 0xc1, 0x51, 0x00, 0x4e, 0xa9, 0xcc, 0x36, 0x5f, 0xed, 0x8c, 0x8c, 0x27, 0xd8, 0x80,
	0xa3, 0x11, 0x19, 0x6d, 0x6a, 0x48, 0x0e, 0xc7, 0xea, 0x8c, 0x07, 0x7d, 0x71, 0xc8, 0x28, 0x95,
	0xd9, 0x75, 0x96, 0x63, 0xd1, 0x27, 0x5d, 0xd1, 0x7f, 0x5a, 0xe0, 0x1d, 0x91, 0x45, 0xcf, 0xa1,
	0x9f, 0xb0, 0x8c, 0x95, 0xa6, 0xd5, 0xfa, 0xf1, 0x48, 0x37, 0xec, 0x47, 0xbb, 0xf1, 0x23, 0x3c,
	0x63, 0x62, 0x87, 0xcb, 0x19, 0xa3, 0x02, 0xd3, 0x54, 0x0e, 0xe4, 0xe4, 0xa9, 0xb6, 0x74, 0x23,
	0x83, 0x0c, 0x40, 0x0b, 0x5e, 0x15, 0x38, 0x91, 0xa2, 0xb7, 0xca, 0xa1, 0x98, 0x8c, 0xb5, 0xe8,
	0x5b, 0x85, 0x44, 0xc6, 0x83, 0x10, 0xf4, 0xb2, 0x98, 0x0b, 0x43, 0x46, 0xd9, 0x92, 0xaa, 0x60,
	0x55, 0x49, 0xe3, 0x1c, 0x53, 0xb1, 0x8c, 0x73, 0xad, 0xda, 0x8d, 0x3a, 0x68, 0xf0, 0x13, 0x38,
	0x46, 0x32, 0x82, 0x9e, 0xc4, 0x8d, 0x62, 0x65, 0xb7, 0xaa, 0xdb, 0x4f, 0x55, 0x0f, 0xae, 0x60,
	0xb0, 0x12, 0x71, 0x29, 0x70, 0x89, 0xce, 0xc1, 0x4b, 0x58, 0x45, 0x45, 0xca, 0xf6, 0x74, 0x4d,
	0x4c, 0x2e, 0x2f, 0x3a, 0x06, 0x83, 0x1b, 0xe8, 0xcb, 0xdd, 0x2a, 0xe5, 0x50, 0xf4, 0xd8, 0x96,
	0x55, 0x6e, 0x42, 0x1b, 0x00, 0x9d, 0xc1, 0x30, 0x25, 0x5c, 0xc4, 0x34, 0xa9, 0xd7, 0xf4, 0xf0,
	0x0e, 0xfe, 0xb1, 0x00, 0xd6, 0x07, 0x21, 0x8f, 0x52, 0xff, 0xe4, 0xc4, 0xd1, 0xf7, 0xd0, 0xcb,
	0x59, 0x8a, 0xfd, 0x9e, 0x92, 0xf5, 0x95, 0x94, 0xd5, 0xe4, 0x6b, 0x99, 0x0b, 0x96, 0xe2, 0x48,
	0x85, 0xa2, 0x29, 0x8c, 0x34, 0xb9, 0x99, 0x54, 0xe3, 0xf7, 0x55, 0xca, 0x36, 0xd4, 0x2c, 0x8d,
	0x33, 0x3d, 0x39, 0x2c, 0x4d, 0x10, 0xc2, 0xf8, 0x38, 0x1f, 0x3a, 0x85, 0xe1, 0x9b, 0xf7, 0xab,
	0xf5, 0xcd, 0x72, 0x36, 0x9f, 0x7c, 0x86, 0x86, 0xd0, 0x5b, 0xbf, 0x5f, 0xcc, 0x27, 0x56, 0xf0,
	0xaf, 0x05, 0x93, 0x3b, 0xc2, 0x67, 0x8c, 0xde, 0x93, 0x6d, 0x55, 0xc6, 0x82, 0x30, 0x2a, 0xdb,
	0xb0, 0x63, 0x5c, 0x8f, 0x50, 0xeb, 0x3b, 0xbc, 0xe5, 0x49, 0xf8, 0x48, 0xb8, 0x72, 0xd9, 0xfa,
	0x24, 0x98, 0x27, 0x7a, 0x01, 0x70, 0x5f, 0x65, 0x19, 0x4f, 0x4a, 0x8c, 0xa9, 0x92, 0x3f, 0x8c,
	0x5a, 0x08, 0x0a, 0xe1, 0x59, 0x89, 0x39, 0xcb, 0x2a, 0x59, 0xe3, 0x77, 0x92, 0x8a, 0x9d, 0x6a,
	0x85, 0x17, 0x75, 0x61, 0x74, 0x01, 0x93, 0x06, 0x7a, 0x87, 0xc9, 0x76, 0x57, 0x6b, 0xff, 0x1f,
	0x2e, 0xab, 0xe6, 0xec, 0x23, 0xa1, 0xdb, 0x0f, 0x94, 0x08, 0xdf, 0x51, 0x51, 0x2d, 0xe4, 0xe2,
	0x25, 0x38, 0x7a, 0x79, 0xa4, 0xe8, 0xc5, 0xcd, 0x2f, 0x52, 0x3e, 0x80, 0xf3, 0x76, 0xae, 0x6c,
	0x0b, 0xb9, 0xd0, 0xff, 0x75, 0xfd, 0x6e, 0x1e, 0x4d, 0xec, 0xeb, 0xbf, 0x6d, 0x18, 0xac, 0xf4,
	0x71, 0x44, 0x57, 0xe0, 0x2d, 0xf1, 0xbe, 0x35, 0xef, 0xf1, 0xf1, 0xbc, 0xce, 0x3a, 0x6f, 0xf4,
	0x02, 0x06, 0x4b, 0xbc, 0x57, 0x07, 0x6c, 0xa8, 0x4e, 0x4a, 0x9c, 0xe0, 0x33, 0x57, 0x5a, 0xea,
	0xb4, 0xa2, 0x6f, 0xc0, 0x55, 0x2b, 0xab, 0x22, 0x46, 0x12, 0x37, 0x1b, 0xdc, 0x0e, 0x0a, 0xc1,
	0x55, 0xf7, 0x57, 0x05, 0x4d, 0x24, 0xde, 0x3e, 0xc7, 0xed, 0xc8, 0x2b, 0x38, 0xad, 0x67, 0x86,
	0xef, 0x08, 0x47, 0xcf, 0xa5, 0xab, 0x3b, 0xc8, 0xf6, 0x0f, 0x2e, 0x00, 0x6e, 0xb1, 0xa8, 0xaf,
	0xe0, 0xb8, 0xb9, 0x7a, 0xf2, 0x93, 0x3f, 0x6b, 0x5d, 0xc1, 0xd7, 0x16, 0x7a, 0x05, 0xe3, 0x5b,
	0x2c, 0x1a, 0x71, 0x1c, 0x35, 0x89, 0xba, 0xc2, 0x5f, 0x5b, 0xd7, 0x7f, 0x59, 0xfa, 0xeb, 0xe2,
	0xe8, 0x1c, 0xe0, 0x43, 0x91, 0xc6, 0x02, 0x2b, 0x01, 0x6e, 0xdd, 0x87, 0xb6, 0xc6, 0xd0, 0x92,
	0x51, 0x6f, 0x09, 0x25, 0x7c, 0xd7, 0xf4, 0xc2, 0xf0, 0x6a, 0x13, 0xfe, 0x16, 0x46, 0xab, 0x1d,
	0xdb, 0xd7, 0x8c, 0x9f, 0x0a, 0xfb, 0x5a, 0x9e, 0x02, 0x56, 0xc8, 0x1e, 0xb4, 0x48, 0x36, 0xe6,
	0xc6, 0x51, 0xff, 0x73, 0x3f, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x11, 0xa5, 0x12, 0xb7, 0xf8,
	0x06, 0x00, 0x00,
}
